version: "3.6"

services:
  spark-master:
    image: ${FUND_IMAGE}:${FUND_IMAGE_VERSION}
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "9090:8080"

networks:
  default:
    external:
      name: prod
