version: '3'
services:
  nginx:
    restart: always
    container_name: nginx-prod
    image: xy/nginx:0.0.0
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx
      - ./cron:/etc
      - ./logrotate:/etc/logrotate.d
    command: service cron start && nginx -g 'daemon off;'

networks:
  default:
    external:
      name: prod
